[package]
authors = ["rchaser53 <tayoshizawa29@gmail.com>"]
name = "like_cron"
version = "0.1.0"

[dependencies]
futures = "0.1.18"
hyper = "0.10.13"
native-tls = "0.1"
serde_json = "1.0.9"
tokio-core = "0.1.12"
tokio-io = "0.1.4"
tokio-tls = "0.1"
