[package]
authors = ["rchaser53 <tayoshizawa29@gmail.com>"]
name = "like_cron"
version = "0.1.0"

[dependencies]
futures = "0.1.18"
hyper = "0.10"
hyper-native-tls = "0.2.4"
serde_json = "1.0.9"
tokio-core = "0.1.12"
