[package]
authors = ["rchaser53 <tayoshizawa29@gmail.com>"]
name = "like_cron"
version = "0.1.0"

[dependencies]
futures = "0.1.17"
hyper = "0.11.8"
hyper-tls = "0.1.2"
job_scheduler = "1.0.4"
rocket = "0.3.3"
rocket_codegen = "0.3.3"
serde_json = "1.0.7"
tokio-core = "0.1.10"
